name: BookShelf
options:
  bundleIdPrefix: com.justinleung
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    GENERATE_INFOPLIST_FILE: YES

targets:
  BookShelf:
    type: application
    platform: iOS
    sources:
      - BookShelf
    settings:
      base:
        INFOPLIST_FILE: BookShelf/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.justinleung.bookshelf
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_NSCameraUsageDescription: "BookShelf needs camera access to scan book barcodes and covers"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    preBuildScripts:
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        shell: /bin/sh
        script: |
          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
  BookShelfTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - BookShelfTests
    dependencies:
      - target: BookShelf
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.justinleung.bookshelf.tests
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
